### ISSUE TITLE
Exceptions in tensorboard logs

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/BeaconK8sUtilities.jl#7]
Seems like definitely an upstream bug. Not sure if the threading bit is relevant; could try without threading. Not sure it actually affects anything either.
```bash
TensorFlow installation not found - running with reduced feature set.
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.6.0 at http://localhost:6006/ (Press CTRL+C to quit)
Exception in thread Reloader 1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 233, in Worker
    accumulator.Reload()
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 177, in Reload
    for event in self._generator.Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 87, in Load
    for event in self._LoadInternal():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 117, in _LoadInternal
    for event in self._loader.Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 189, in Load
    for event in super(EventFileLoader, self).Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 163, in Load
    for record in super(LegacyEventFileLoader, self).Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 138, in Load
    yield next(self._iterator)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 109, in __next__
    self._reader.GetNext()
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 230, in GetNext
    event_str = self._read(header_len)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 273, in _read
    new_data = self.file_handle.read(n)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 482, in read
    self.filename, self.binary_mode, read_size, self.continuation_token
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 277, in read
    stream = s3.Object(bucket, path).get(**args)["Body"].read()
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

Exception in thread Reloader 2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 233, in Worker
    accumulator.Reload()
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 177, in Reload
    for event in self._generator.Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 87, in Load
    for event in self._LoadInternal():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 117, in _LoadInternal
    for event in self._loader.Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 189, in Load
    for event in super(EventFileLoader, self).Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 163, in Load
    for record in super(LegacyEventFileLoader, self).Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 138, in Load
    yield next(self._iterator)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 109, in __next__
    self._reader.GetNext()
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 230, in GetNext
    event_str = self._read(header_len)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 273, in _read
    new_data = self.file_handle.read(n)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 482, in read
    self.filename, self.binary_mode, read_size, self.continuation_token
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 277, in read
    stream = s3.Object(bucket, path).get(**args)["Body"].read()
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

Exception in thread Reloader:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/data_ingester.py", line 98, in _reload
    self._multiplexer.AddRunsFromDirectory(path, name)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 202, in AddRunsFromDirectory
    self.AddRun(subdir, name=subname)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 167, in AddRun
    accumulator.Reload()
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 177, in Reload
    for event in self._generator.Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 87, in Load
    for event in self._LoadInternal():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 117, in _LoadInternal
    for event in self._loader.Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 189, in Load
    for event in super(EventFileLoader, self).Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 163, in Load
    for record in super(LegacyEventFileLoader, self).Load():
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 138, in Load
    yield next(self._iterator)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 109, in __next__
    self._reader.GetNext()
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 230, in GetNext
    event_str = self._read(header_len)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 273, in _read
    new_data = self.file_handle.read(n)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 482, in read
    self.filename, self.binary_mode, read_size, self.continuation_token
  File "/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 277, in read
    stream = s3.Object(bucket, path).get(**args)["Body"].read()
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

**Comment by ericphanson** [comment]
I think this is because our code was accidentally deleting tensorboad logs on s3, so the `NoSuchKey`s were legit!
